version: '3.8'

services:
  gurus-das-rotinas:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "18020:18020"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - PORT=18020
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.5'
          memory: 128M
