GET http://localhost:18020/api/healthz/ HTTP/1.1
Content-Type: application/json


###
POST http://localhost:18020/api/find-service HTTP/1.1
Content-Type: application/json

{"intent":"agendar uma consulta"}