services:
  backend-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=8080
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    ports:
      - "18020:8080"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: "128MB"